ejemplo_clase/marvel/e_commerce/api/urls.py
from django.urls import path
from e_commerce.api.marvel_api_views import *

# Importamos las API_VIEWS:
from e_commerce.api.api_views import *

urlpatterns = [
    # User APIs:
    path('user/login/', LoginUserAPIView.as_view()),

    # APIs de Marvel
    path('get-comics/',get_comics, name='get-comics'),
    path('purchased-item/',purchased_item, name='purchased-item'),
    
    # Comic API View:
    path('comics/get', GetComicAPIView.as_view()),
    path('comics/post', PostComicAPIView.as_view()),
    path('comics/get-post', ListCreateComicAPIView.as_view()),
    path('comics/<pk>/update', RetrieveUpdateComicAPIView.as_view()),
    path('comics/<pk>/delete', DestroyComicAPIView.as_view()),

    # Wish-list API View
    path('Wish/get', GetWishListAPIView.as_view()),
    path('Wish/post', PostWishListAPIView.as_view()),

    # Chatbot API View:
    path('chatbot', ChatbotAPIView.as_view(), name='chatbot'),
]

ejemplo_clase/marvel/e_commerce/urls.py
from django.urls import path
from e_commerce.api.marvel_api_views import *

# Importamos las API_VIEWS:
from e_commerce.views import *

# Librerías para el manejo de sesión.
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

# Una forma de listar endpoints para redirección. 
# Django posee su propia herramienta para esto: 
# Django redirects app: https://docs.djangoproject.com/en/3.2/ref/contrib/redirects/#module-django.contrib.redirects 

INDEX_LIST = ['index/', 'index/#', '']
INDEX_PATTERNS = [path(x, IndexView.as_view()) for x in INDEX_LIST]

urlpatterns = [
    # NOTE: e-commerce base:
    path('base', BaseView.as_view()),

    # NOTE: Manejo de sesión:
    path('login', auth_views.LoginView.as_view(template_name='e-commerce/login.html', redirect_authenticated_user=True, redirect_field_name='index'), name='login'
         ),
    path('logout', auth_views.LogoutView.as_view(next_page='/e-commerce/index', redirect_field_name='index'),
         ),
    path('signup', register, name='register'),

    # NOTE: Páginas del sitio:
    path('detail', DetailsView.as_view(), name='detail'),
    path('index', IndexView.as_view(), name='index'),
    path('thanks', ThanksView.as_view(), name='thanks'),
    path('update-user', UpdateUserView.as_view(), name= 'update'),
    path('user', login_required(UserView.as_view()), name= 'user'),
    path('wish', login_required(WishView.as_view()), name='wish'),
    path('cart', login_required(CartView.as_view()), name='cart'),

    # NOTE: Formularios ocultos
    path('checkbutton', check_button, name='checkbutton'),

    # NOTE: Ejemplos de Bootstrap HTML:
    path('bootstrap-login', BootstrapLoginUserView.as_view(), name='loginbootstrap'),
    path('bootstrap-signup', BootstrapSignupView.as_view(), name='signupbootstrap'),
    path('help', HelpView.as_view(),name='help') ,

]
urlpatterns += INDEX_PATTERNS

ejemplo_clase/marvel/marvel/urls.py
from django.contrib import admin
from django.urls import path, include
# NOTE: importamos Templateview para darle una view a Swagger 
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view



description = '''
<img src="https://lh3.googleusercontent.com/pw/AM-JKLWLct73ne_PgqQ146YMYjUgbswqg703xPZPnVImkFYwGbao5YksFGJFOlcoCJLfqIJ9_LRwFAwP9qinoEvsLx92NTOfAn54SgMLTgMvtii0r_rjneGjR53bx08OCncv4mRH4gNnpmEUuKofj59L9dAv=w1257-h103-no?authuser=0">
</br>
</br>
<h2>Documentación general de APIs de la aplicación e-commerce</h2>
<p>Para la autenticación por medio de TOKENS debemos agregar en el header:
</br>
<ul><li>'Authorization': 'Token 92937874f377a1ea17f7637ee07208622e5cb5e6'</li></ul>
</br>
Donde 92937874f377a1ea17f7637ee07208622e5cb5e6 es un ejemplo del Token Key. 
</p>
'''


urlpatterns = [
    # Django default urls:
    path('admin/', admin.site.urls),

    # e-commerce app urls:
    path('e-commerce/',include('e_commerce.api.urls')),
    path('e-commerce/',include('e_commerce.urls')),
    
    # swagger app urls:
    path('api-docs/', TemplateView.as_view(
        template_name='api-docs/swagger-ui.html',
        extra_context={'schema_url':'openapi-schema'}
    ), name='swagger-ui'),
     path('openapi', get_schema_view(
        title="Inove Marvel e-commerce",
        description=description,
        version="1.0.0"
    ), name='openapi-schema'),
]

ejemplo_clase/marvel/e_commerce/models.py
from django.db import models

# NOTE: Para poder utilizar el modelo "user" que viene por defecto en Django,
# Debemos importarlo previamente:

from django.contrib.auth.models import User

# Create your models here.


class Comic(models.Model):
    '''
    Esta clase hereda de Django models.Model y crea una tabla llamada
    e_commerce_comic. Las columnas toman el nombre especificado de cada objeto.
    '''
    id = models.BigAutoField(db_column='ID', primary_key=True)
    marvel_id = models.PositiveIntegerField(
        verbose_name='marvel ids', default=1, unique=True)
    title = models.CharField(
        verbose_name='titles', max_length=120, default='')
    description = models.TextField(
        verbose_name='descriptions', default='')
    price = models.FloatField(
        verbose_name='prices', max_length=5, default=0.00)
    stock_qty = models.PositiveIntegerField(
        verbose_name='stock qty', default=0)
    picture = models.URLField(
        verbose_name='pictures', default='')

    class Meta:
        '''
        Con "class Meta" podemos definir atributos de nuestras entidades como el nombre de la tabla.
        '''
        db_table = 'e_commerce_comics'

    def __str__(self):
        '''
        La función __str__ cumple la misma función que __repr__ en SQL Alchemy, 
        es lo que retorna cuando llamamos al objeto.
        '''
        return f'{self.id}'


class WishList(models.Model):
    id = models.BigAutoField(db_column='ID', primary_key=True)
    user_id = models.ForeignKey(User,
                                verbose_name='User',
                                on_delete=models.DO_NOTHING,
                                default=1, blank=True
                                )
    comic_id = models.ForeignKey(Comic,
                                 verbose_name='Comic',
                                 on_delete=models.DO_NOTHING,
                                 default=1, blank=True
                                 )
    favorite = models.BooleanField(
        verbose_name='Favorite', default=False)
    cart = models.BooleanField(
        verbose_name='carts', default=False)
    wished_qty = models.PositiveIntegerField(
        verbose_name='wished qty', default=0)
    buied_qty = models.PositiveIntegerField(
        verbose_name='buied qty', default=0)

    class Meta:
        db_table = 'e_commerce_wish_list'

    def __str__(self):
        return f'{self.id}'

ejemplo_clase/marvel/e_commerce/views.py
# Importamos vistas genericas:
from django.views.generic import TemplateView, ListView

# Importamos los modelos que vamos a usar:
from django.contrib.auth.models import User
from e_commerce.models import *


# Formulario de registro:
from django import forms
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm

# Utilidades:
from marvel.settings import VERDE, AMARILLO

# NOTE: Páginas del sitio **********************************************************

class BaseView(TemplateView):
    '''
    Template base que vamos a extender para el resto de las páginas del sitio.
    '''
    template_name = 'e-commerce/base.html'


class LoginUserView(TemplateView):
    '''
    Formulario de inicio de sesión.
    '''
    template_name = 'e-commerce/login.html'

class UserForm(UserCreationForm):
    '''
    Formulario de creación de usuario.
    Utilizamos un formulario que viene por defecto en Django y que cumple con todos los
    requisitos para agregar un nuevo usuario a la base de datos.
    También tiene los métodos para validar todos sus campos.
    '''
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')


def register(request):
    '''
    Función que complementa el formulario de registro de usuario.
    Al completar el formulario, se envía la información a esta función que espera
    una petición de tipo `POST`, si la información enviada no es valida o la petición no es POST, 
    se redirige nuevamente a la página de registro. Si el registro fue exitoso,
    el usuario será redirigido a la página de logueo.
    '''
    if request.method == 'POST':
        # Si la petición es de tipo POST, analizamos los datos del formulario:
        # Creamos un objeto de tipo UserForm (la clase que creamos mas arriba)
        # Pasandole los datos del request:
        form = UserForm(request.POST)
        # Luego, utilizamos el método que viene en en la clase UserCreationForm
        # para validar los datos del formulario: 
        [print(VERDE+'',item) for item in form] # NOTE: Imprimimos para ver el contenido del formulario COMPLETO
        if form.is_valid():
            # Si los datos son validos, el formulario guarda los datos en la base de datos.
            # Al heredar de UserCreationForm, aplica las codificaciónes en el password y todo
            # lo necesario:
            form.save()
            # Con todo terminado, redirigimos a la página de inicio de sesión,
            # porque por defecto, registrar un usuario no es iniciar una sesión.
            return redirect('/e-commerce/login')
    else:
        # Si el método no es de tipo POST, se crea un objeto de tipo formulario
        # Y luego se envía al contexto de renderización. 
        form = UserForm()
    # Si los datos del POST son invalidos o si el método es distinto a POST
    # retornamos el render de la página de registro, con el formulario de registro en el contexto.
    [print(AMARILLO+'',item) for item in form] # NOTE: Imprimimos para ver el contenido del formulario vacío
    return render(request, 'e-commerce/signup.html', {'form': form})

class IndexView(ListView):
    '''
    Página principal del sitio.
    Utilizamos `ListView` para poder aprovechar sus funciones de paginado.
    Para ello tenemos que utilizar sus atributos:
    \n
    '''
    queryset = Comic.objects.all().order_by('-id')
    # NOTE: Este queryset incorporará una lista de elementos a la que le asignará
    # Automáticamente el nombre de comic_list
    template_name = 'e-commerce/index.html'
    paginate_by = 10

    # NOTE: Examinamos qué incluye nuestro contexto:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        [print(AMARILLO+f'{element}\n') for element in context.items()]
        return context


class DetailsView(TemplateView):
    template_name = 'e-commerce/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            comic_obj = Comic.objects.get(
                marvel_id=self.request.GET.get('marvel_id'))
            context["comic"] = comic_obj
            context['comic_picture_full'] = str(
                comic_obj.picture).replace('/standard_xlarge', '')
            context['comic_desc'] = str(
                comic_obj.description).replace('<br>', '\n')
            username = self.request.user
            if username != None:
                user_obj = User.objects.filter(username=username)
                if user_obj.first() != None:
                    wish_obj = WishList.objects.filter(
                        user_id=user_obj[0].id, comic_id=comic_obj)
                    if wish_obj.first() != None:
                        context["favorite"] = wish_obj.first().favorite
                        context["cart"] = wish_obj.first().cart
                        context["wished_qty"] = wish_obj.first().wished_qty
                    else:
                        context["favorite"] = False
                        context["cart"] = False
                        context["wished_qty"] = 0
        except:
            return context
        return context


def check_button(request):
    '''
    Esta función tiene como objetivo el cambio de estado de los botones de favoritos y carrito.
    '''
    if request.method == 'POST':
        print(request.path)
        # NOTE: Obtenemos los datos necesarios:
        username = request.POST.get('username')
        marvel_id = request.POST.get('marvel_id')
        user_authenticated = request.POST.get('user_authenticated')
        type_button = request.POST.get('type_button')
        actual_value = request.POST.get('actual_value')
        path = request.POST.get('path')

        # Validamos los datos y les damos formato:
        username = username if username != '' else None
        marvel_id = marvel_id if marvel_id != '' else None
        user_authenticated = True if user_authenticated == 'True' else False
        type_button = type_button if type_button != '' else None
        actual_value = True if actual_value == 'True' else False
        path = path if path != None else 'index'

        if user_authenticated and username != None:
            # Si el usuario está autenticado, traemos su "wishlist"
            user_obj = User.objects.get(username=username)
            comic_obj = Comic.objects.get(marvel_id=marvel_id)
            wish_obj = WishList.objects.filter(
                user_id=user_obj, comic_id=comic_obj).first()
            if not wish_obj:
                # Si no tiene "wishlist" creamos una
                wish_obj = WishList.objects.create(
                    user_id=user_obj, comic_id=comic_obj)

            # Remplazamos el estado del botón seleccionado:
            if type_button == "cart":
                wish_obj.cart = not actual_value
                wish_obj.save()
                print('wish_obj.cart :', wish_obj.cart)
            elif type_button == "favorite":
                wish_obj.favorite = not actual_value
                print('wish_obj.favorite :', wish_obj.favorite)
                wish_obj.save()
            else:
                pass
            # Componemos los endpoints segun la página:
            if 'detail' in path:
                path += f'?marvel_id={marvel_id}'
            
            # Una vez terminada la modificación, volvemos a la misma página.
            return redirect(path)
        else:
            # Si el usuario no está autenticado, lo redirigimos a la página de logueo.
            return redirect('login')
    else:
        # Si por error quisieron acceder al recurso con otro método que no sea POST, lo redirigimos al index
        return redirect('index')


class CartView(TemplateView):
    '''
    Vista de carrito de compras.
    Aquí se listará el total de elementos del carrito del usuario, 
    luego en el template se colocará un formulario en cada elemento del carrito
    para darlo de baja, y un boton general para concretar el pedido.
    '''
    template_name = 'e-commerce/cart.html'

    def get_context_data(self, **kwargs):
        '''
        En el contexto, devolvemos la lista total de elementos en el carrito de compras, 
        y el precio total calculado para la compra.
        '''
        context = super().get_context_data(**kwargs)
        username = self.request.user
        user_obj = User.objects.get(username=username)
        wish_obj = WishList.objects.filter(user_id=user_obj, cart=True)
        cart_items = [obj.comic_id for obj in wish_obj]
        context['cart_items'] = cart_items
        context['total_price'] = round((sum([float(comic.price) for comic in cart_items])), 2)
        print(context['cart_items'])
        return context


class WishView(TemplateView):
    '''
    En esta vista vamos a traer todos los comics favoritos de un usuario en particular.
    Luego en el Template vamos a colocar un formulario por cada favorito, 
    para eliminarlo de la lista de favoritos.
    '''
    template_name = 'e-commerce/wish.html'

    def get_context_data(self, **kwargs):
        '''
        Preparamos en nuestro contexto la lista de comics del usuario registrado.
        '''
        context = super().get_context_data(**kwargs)
        username = self.request.user
        user_obj = User.objects.get(username=username)
        wish_obj = WishList.objects.filter(user_id=user_obj, favorite=True)
        cart_items = [obj.comic_id for obj in wish_obj]
        context['fav_items'] = cart_items
        print(context['fav_items'])
        return context


class ThanksView(TemplateView):
    '''
    Página de agradecimiento. Esta es la página de respuesta una vez realizado el pedido.
    El Template tiene que tener un botón de redireccionamiento al index.

ejemplo_clase/marvel/templates/e-commerce/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    {% block head %}

    {% endblock head %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'e-commerce/css/base.css' %}">
    <title>{% block title %}Marvel e-commerce{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        <img id="logo" src="{% static 'e-commerce/img/marvel.svg' %}" alt="My image" width="15%" height="10%">
        <br>
        {% block sidebar %}
        | <a href="/e-commerce/index">Comics</a>
        {% if user.is_authenticated %}
        | <a href="/e-commerce/logout">Logout</a>
        | <a href="/e-commerce/user">User profile</a>
        | <a href="/e-commerce/cart">Cart</a>
        | <a href="/e-commerce/wish">Wishes</a>
        {% else %}
        | <a href="/e-commerce/login">Login</a>
        | <a href="/e-commerce/signup">Sign up!</a>
        {% endif %}
        | <a href="/e-commerce/help">Help</a>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <footer>

        <div id="footer">
            <h4>Esta aplicación fue desarrollada como parte del curso "Python Django" en <a
                    href="https://www.inove.com.ar">  Inove - coding school</a></h4>
        </div>

    </footer>
</body>

</html>

ejemplo_clase/marvel/templates/e-commerce/bootstrap-login.html
{% extends 'e-commerce/base.html' %}

{% block head %}
<!-- Importamos lo principal -->
{% load  static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'e-commerce/css/base.css' %}">
<title>{% block title %}Marvel e-commerce{% endblock %}</title>

<!-- Importamos Bootstrap en el head de nuestro HTML -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock head %}
    

{% block content %}
<h1>Bootstrap Login !</h1>

<form action="{% url 'login' %}" method="POST">{%csrf_token%}
    <div class="mb-3">
      <label for="username" class="form-label">username</label>
      <input type="text" class="form-control" id="username" name="username" value="Leon">
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" class="form-control" id="password" name="password" value="Kennedy">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock content %}

ejemplo_clase/marvel/templates/e-commerce/bootstrap-signup.html
{% extends 'e-commerce/base.html' %}

{% block head %}
<!-- Importamos lo principal -->
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'e-commerce/css/base.css' %}">
<title>{% block title %}Marvel e-commerce{% endblock %}</title>

<!-- Importamos Bootstrap en el head de nuestro HTML -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
{% endblock head %}


{% block content %}
<h1>Bootstrap Sign Up !</h1>


<form action="signup" method="POST">{%csrf_token%}
    <div class="mb-3">
        <p><label class="form-label" for="id_first_name">First name:</label> <input class="form-control" type="text"
                name="first_name" required id="id_first_name">
        </p>
    </div>
    <div class="mb-3">
        <p><label class="form-label" for="id_last_name">Last name:</label>
            <input class="form-control" type="text" name="last_name" required id="id_last_name">
        </p>
    </div>
    <div class="mb-3">
        <p><label class="form-label" for="id_username">Nombre de usuario:</label> <input class="form-control"
                type="text" name="username" maxlength="150" autofocus required id="id_username"> <span
                class="helptext">Requerido. 150 carácteres como máximo. Únicamente letras,
                dígitos y @/./+/-/_ </span></p>

    </div>
    <div class="mb-3">
        <p><label class="form-label" for="id_email">Email:</label> <input class="form-control" type="email" name="email"
                required id="id_email"></p>

    </div>
    <div class="mb-3">
        <p><label class="form-label" for="id_password1">Contraseña:</label> <input class="form-control" type="password"
                name="password1" autocomplete="new-password" required id="id_password1"> <span class="helptext">
                <ul>
                    <li>Su contraseña no puede asemejarse tanto a su otra información personal.</li>
                    <li>Su contraseña debe contener al menos 8 caracteres.</li>
                    <li>Su contraseña no puede ser una clave utilizada comúnmente.</li>
                    <li>Su contraseña no puede ser completamente numérica.</li>
                </ul>
            </span></p>
    </div>
    <div class="mb-3">

        <p><label class="form-label" for="id_password2">Contraseña (confirmación):</label> <input class="form-control"
                type="password" name="password2" autocomplete="new-password" required id="id_password2"> <span
                class="helptext">Para verificar,
                introduzca la
                misma contraseña anterior.</span></p>
    </div>
    <br>
    <div class="mb-3">
        <input class="btn btn-primary" type="submit" value="Register" />
    </div>
</form>

{% endblock content %}

ejemplo_clase/marvel/templates/e-commerce/cart.html
{% extends "e-commerce/base.html" %}
{% block title %}Carrito{% endblock %}
{% block content %}
{% load static %}

<h1>{{user.username}} este es tu carrito de compras, puedes confirmar el pedido o eliminar elementos de tu carrito.</h1>

<table>

    {% for comic in cart_items %}
    <tr class="comic-item">
        <td>
            <a href="/e-commerce/detail?marvel_id={{comic.marvel_id}}">
                <img src="{{comic.picture}}" alt="Not found">
            </a>
        </td>
        <td>
            <ul>
                <li>
                    <h2>{{comic.title}}</h2>
                </li>
                <li>
                    <h2>Precio unitario: U$S {{comic.price}}</h2>
                </li>
            </ul>
        </td>
        <td>
            <form action="{% url 'checkbutton' %}" method="POST">{%csrf_token%}
                <input type="hidden" name="username" value="{{user.username}}">
                <input type="hidden" name="marvel_id" value="{{comic.marvel_id}}">
                <input type="hidden" name="user_authenticated" value="{{user.is_authenticated}}">
                <input type="hidden" name="type_button" value="cart">
                <input type="hidden" name="actual_value" value="True">
                <input type="hidden" name="path" value="cart">
                <input type="hidden" name="path" value="{% url 'cart' %}">
                <input type="image" src="{% static 'e-commerce/img/cart-true.png' %}" width="60%">
            </form>

            <p>(Quitar de carrito)</p>
        </td>
    </tr>

    {% endfor %}

    <td>
        <h1>Precio total: U$S {{total_price}}</h1>
    </td>
    <td style="text-align: center;">
        <a  href="{% url 'thanks' %}">
            <h1>-> Confirmar pedido <- </h1>
        </a>
    </td>
</table>

{% endblock %}

ejemplo_clase/marvel/templates/e-commerce/detail.html
{% extends "e-commerce/base.html" %}

{% block title %}Detalle de producto{% endblock %}

{% block content %}
{% load static %}
<div class="comic-grid">

    <div class="comic-item">
        <img src="{{comic_picture_full}}" alt="Not Found ...">
    </div>
    <div class="comic-item">
        <h1>
            {{comic.title}}
        </h1>
        <h2>
            {% if comic_desc == "None" %}
            Descripción no disponible.
            {% else %}
            {{comic_desc}}
            {% endif %}
        </h2>
        <div class="price-item">
            Precio: U$S {{comic.price}}
        </div>
        <div id="grid-buttons">
            <div class="grid-button-item">

                <form action="{% url 'checkbutton' %}" method="POST">{%csrf_token%}

                    <input type="hidden" name="username" value="{{user.username}}">
                    <input type="hidden" name="marvel_id" value="{{comic.marvel_id}}">
                    <input type="hidden" name="user_authenticated" value="{{user.is_authenticated}}">
                    <input type="hidden" name="type_button" value="cart">
                    <input type="hidden" name="actual_value" value="{{cart}}">  
                    <input type="hidden" name="path" value="{% url 'detail' %}">  
                    
                    {% if cart %}
                    <input type="image" src="{% static 'e-commerce/img/cart-true.png' %}">
                    {% else %}
                    <input type="image" src="{% static 'e-commerce/img/cart-false.png' %}">
                    {% endif %}
                    
                </form>
                
            </div>
            <div class="grid-button-item">
                
                <form action="{% url 'checkbutton' %}" method="POST">{%csrf_token%}
                    
                    <input type="hidden" name="username" value="{{user.username}}">
                    <input type="hidden" name="marvel_id" value="{{comic.marvel_id}}">
                    <input type="hidden" name="user_authenticated" value="{{user.is_authenticated}}">
                    <input type="hidden" name="type_button" value="favorite">
                    <input type="hidden" name="actual_value" value="{{favorite}}">  
                    <input type="hidden" name="path" value="{% url 'detail' %}">  
                    
                    {% if favorite %}
                        <input type="image" src="{% static 'e-commerce/img/favs-true.png' %}">
                    {% else %}
                        <input type="image" src="{% static 'e-commerce/img/favs-false.png' %}">
                    {% endif %}
                
                </form>
            </div>


        </div>

    </div>

</div>




{% endblock %}

ejemplo_clase/marvel/templates/e-commerce/index.html
{% extends "e-commerce/base.html" %}

{% block title %}index{% endblock %}

{% block content %}
<!-- Lista de comics: -->
<div class='grid-container'>
    {% for comic in comic_list %}
    <div class="grid-item">
        <div class="comic-block">

            <a href="detail?marvel_id={{comic.marvel_id}} ">
                <img class='comic_img' src="{{comic.picture}}" alt="Not found :C">
            </a>
            <h3>
                {{comic.title}}
            </h3>
            <div class="price">
                <p>
                    Precio: U$S {{comic.price}} -
                    Stock:
                    {% if comic.stock_qty > 0 %}
                    {{comic.stock_qty}}</p>
                {% else %}
                <h3>Agotado!</h3>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Paginado: -->

<div class="paginator-content">
    <div class="paginator-item">

        {% if page_obj.has_previous %}
        <a class="page-btn" href="?page=1">First ( 1 )</a>
        {% endif %}


    </div>
    <div class="paginator-item">
        {% if page_obj.has_previous %}
        <a class="page-btn" href="?page={{page_obj.previous_page_number}}"><- Prev</a>
        {% endif %}
    </div>
    <div class="paginator-item">
        <div class="page-btn">
        <a class="page-btn" href=""> {{page_obj.number}}</a>

        </div>
    </div>
    <div class="paginator-item">
        {% if page_obj.has_next %}
        <a class="page-btn" href="?page={{page_obj.next_page_number}}"> Next -></a>
        {% endif %}
    </div>
    <div class="paginator-item">
        {% if page_obj.has_next %}
        <a class="page-btn" href="?page={{page_obj.paginator.num_pages}}">Last ( {{page_obj.paginator.num_pages}} )</a>
        {% endif %}
    </div>

</div>

<!-- Ejemplo de paginado con un bucle:
{% for page in page_obj.paginator.page_range %}
    <a href="?page={{page}}">{{page}}</a>
{% endfor %} -->
    


{% endblock %}

ejemplo_clase/marvel/templates/e-commerce/login.html
{% extends 'e-commerce/base.html' %}


{% block content %}
<h1>Login !</h1>
<form action="{% url 'login' %}" method="POST">{%csrf_token%}
    <label for="username">Username:</label><br>
    <input type="text" id="username" name="username" value="Leon"><br>
    <label for="password">Password:</label><br>
    <input type="password" id="password" name="password" value="Kennedy"><br><br>
    <input type="submit" value="Enviar">
</form>
{% endblock content %}